### ISSUE TITLE
Upgrade tag ?

### ISSUE THREAD

**Issue by Alahel** [grainrigi/async-singleton#3]
Hello  @grainrigi ;) could it be possible to create a tag 1.1.0 & publish on npm (https://github.com/grainrigi/async-singleton/issues/2) ? Thanks a lot

**Comment by grainrigi** [comment]
Sorry, I've forgot to do that.
Please use 1.1.1. (I accidentally published old build for 1.1.0)

**Comment by Alahel** [comment]
Thanks a lot
